### ISSUE TITLE
cannot run tests

### ISSUE THREAD

**Issue by geritol** [infernojs/create-inferno-app#59]
Hi!
I did a fresh app through the CLI and the command npm test (or yarn test) do not work.
I am getting the following error message:
`Determining test suites to run...Error: This promise must be present when running with -o.
    at my-project/node_modules/jest-cli/build/search_source.js:202:17
    at Generator.next (<anonymous>)
    at step (my-project/node_modules/jest-cli/build/search_source.js:19:362)
    at my-project/node_modules/jest-cli/build/search_source.js:19:592
    at new Promise (<anonymous>)
    at my-project/node_modules/jest-cli/build/search_source.js:19:273
    at SearchSource.getTestPaths (my-project/node_modules/jest-cli/build/search_source.js:216:10)
    at my-project/node_modules/jest-cli/build/run_jest.js:44:29
    at Generator.next (<anonymous>)
    at step (my-project/node_modules/jest-cli/build/run_jest.js:23:380)`

**Comment by Havunen** [comment]
Sounds like bug

**Comment by Havunen** [comment]
I have rebased all updates from the upstream, updated all the depencies to latest versions and converted the source code to ESM.
The next major version will require Node 20 or newer.
This issue most likely has disappeared or changed.
